Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,60 +7,65 @@
 #     +-===== [[ linuxcode.org - github.com/alintamvanz
 #
 
-m="\033[1;31m"
-k="\033[1;33m"
-h="\033[1;32m"
-b="\033[1;34m"
-n="\033[1;0m"
+KAGARI_WORK_DIR="/opt/kagari"
 
-kagari_load(){
-{
-for (( i = $2 ; i <= $3 ; i++ )); do
-	sleep 0.1
-	echo "$i"
-done
- } | whiptail --backtitle "KAGARI v1.8 codename Penikung" --title "KAGARI v1.8  - Penikung" --gauge "$1" 11 88 0
-}
-kagari_about(){
-whiptail --backtitle "KAGARI v1.8 codename Penikung" --textbox about.txt --scrolltext --title "kagari - about us" 30 80 0
-}
-kagari_license(){
- whiptail --backtitle "KAGARI v1.8 codename Penikung" --textbox LICENSE.txt --scrolltext --title "kagari - General Public License v3" 40 88 0
-}
-kagari_install(){
-	kagari_load "[!] INSTALLING KAGARI PLEASE WAIT :* ..." 0 100
-	mkdir -p /opt/kagari
-	chmod 755 -R /opt/kagari
-	cp -r * /opt/kagari
-	cp autorun.sh /usr/bin/kagari
-	chmod 755 /usr/bin/kagari
-}
-kagari_uninstall(){
-	kagari_load "[!] UNINSTALLING KAGARI ..." 0 100
-	rm -rf /opt/kagari
+case $1 in
+	"-h" )
+cat $KAGARI_WORK_DIR/help.txt > /dev/null 2>&1
+    if [[ "$?" -eq "0" ]]; then
+    	more $KAGARI_WORK_DIR/help.txt
+    else
+    	echo "[!] File $KAGARI_WORK_DIR/help.txt Was missing.."
+    fi
+		;;
+    "--help" )
+cat $KAGARI_WORK_DIR/help.txt > /dev/null 2>&1
+    if [[ "$?" -eq "0" ]]; then
+    	more $KAGARI_WORK_DIR/help.txt
+    else
+    	echo "[!] File $KAGARI_WORK_DIR/help.txt Was missing.."
+    fi
+        ;;
+    "run-pl" )
+perl $KAGARI_WORK_DIR/perl/kagari.pl
+        ;;
+    "run-perl" )
+perl $KAGARI_WORK_DIR/perl/kagari.pl
+        ;;
+    "run-php" )
+php $KAGARI_WORK_DIR/php/kagari.php
+        ;;
+     "run-py" )
+python $KAGARI_WORK_DIR/python/kagari.py
+        ;;
+     "run-python" )
+python $KAGARI_WORK_DIR/python/kagari.py
+        ;;
+    "start" )
+perl $KAGARI_WORK_DIR/kagari2.pl
+        ;;
+    "--uninstall" )
+if [[ `whoami` == "root" ]]; then
+	
+which kagari > /dev/null 2>&1
+if [[ "$?" -eq "0" ]]; then
+	echo "[-] UNINSTALL   : Removing $KAGARI_WORK_DIR/kagari.pl ..."
+	rm $KAGARI_WORK_DIR/kagari.pl
+	sleep 1
+	echo "[-] UNINSTALL   : Removing /usr/bin/kagari ..."
 	rm /usr/bin/kagari
-}
-kagari_main(){
-pil=$(whiptail --menu "[+] What Do You Want [?]" 13 50 0 \
-Install kagari \
-Uninstall kagari \
-Read License \
-About us \
-3>&1 1>&2 2>&3 3>&1 
-)
-clear
-if [[ $pil == "Install" ]]; then
-	kagari_install
-elif [[ $pil == "Uninstall" ]]; then
-	kagari_uninstall
-elif [[ $pil == "About" ]]; then
-	kagari_about
-elif [[ $pil == "Read" ]]; then
-	kagari_license
+	sleep 1
+	echo "[-] UNINSTALL   : Removing $KAGARI_WORK_DIR/*"
+	rm $KAGARI_WORK_DIR/*
+	rmdir $KAGARI_WORK_DIR
+	echo "[-] UNINSTALLED.."
+else
+	echo "[!] Kagari not installed."
 fi
-}
-
-whiptail --backtitle "[PENIKUNG] KAGARI v1.8 Installer" --title "KAGARI v1.8 - Penikung" --msgbox "[*]  Welcome To kagari ! \n[*] Version : 1.8\n[*] Codename : Penikung\n[+]Author : shutdown57 a.k.a alinko" 11 70
-kagari_license
-kagari_about
-kagari_main
+else
+	echo "[+] You must be root to run this command."
+fi
+        ;;
+        *)
+more $KAGARI_WORK_DIR/help.txt
+esac
